### ISSUE TITLE
Define all elements of the DSL

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#104]
Elements that are missing (after this issue)
- SUT (captured in https://github.com/benchflow/benchflow/issues/398)
  - service specific configuration (doesn't add any functionality as can be specified in docker compose file)
- workload
  - driver type: `http` is missing (captured in https://github.com/benchflow/benchflow/issues/375)

 `step function` has been moved to https://github.com/benchflow/benchflow/issues/397

**Comment by VincenzoFerme** [comment]
@jeppe-style please describe what is missing

**Comment by VincenzoFerme** [comment]
Related to the following Slack thread: https://benchflow.slack.com/archives/C5D75QHBN/p1495465359227559

**Comment by jeppe-style** [comment]
@VincenzoFerme I extracted separate issues from this one and suggest to close this in favor of https://github.com/benchflow/benchflow/issues/396
