### ISSUE TITLE
Minio buckets/keys structure to Store the Benchmark Definition

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#208]
_From @VincenzoFerme on December 4, 2015 21:35_

Define the bucket and the keys structure to store the benchmark definitions on Minio.

Follow the ideas and what has been discussed for the naming of the buckets/key used to store the benchmark runs: https://github.com/benchflow/data-transformers/issues/4

_Copied from original issue: benchflow/experiments-manager#8_

**Comment by VincenzoFerme** [comment]
_From @simonedavico on December 6, 2015 9:24_

@VincenzoFerme @Cerfoglg  If we want to be compliant everywhere, I need to implement the same hashing you implemented in that issue. Is it possible to have a description of how you do it, so that I can port it to Java?

Otherwise, just point me to the implementation and I will take a look.

**Comment by VincenzoFerme** [comment]
@simonedavico some notes:
1. You first need to define the key structure you want to use for the data you need to put on Minio. You can write it down in this issue;
2. Then you can use the hashing function. @Cerfoglg already made it available also for Java ;): https://github.com/benchflow/keyname-hash-generator/tree/dev/java

**Comment by VincenzoFerme** [comment]
_From @simonedavico on December 6, 2015 15:41_

Great, thanks @Cerfoglg  and @VincenzoFerme. We just have to decide WHAT we want to hash. I would postpone this until we have some kind of authentication set up, so that we can hash user ID + benchmark name. Hashing benchmark name by itself wouldn't be of much use. My idea is to keep a structure like this:
- `benchmarks/hash(userid + benchmarkName).zip`
- `benchmarks/hash(userid + benchmarkName).config.yml`

**Comment by VincenzoFerme** [comment]
@simonedavico I report in the following some of the design decision we made for https://github.com/benchflow/data-transformers/issues/4 and some questions.

**Design Decisions:** 
- it is general practice that keys follow the same format as a conventional file systems, like for example "folder/subfolder/foobar.txt" refering to a file "foobar.txt". We prepend the key with its hash, thus having this long string as key does not impact too much the performance of retrieving the data;
- the hash value is computed from the key, and is prepended to the key. For example "folder/subfolder/foobar.txt" becames "hash/folder/subfolder/foobar.txt" when the hash is added.

**Questions:** 
- What are the actual advantages of integrating (in a way) the UserID or better the Username in the key? I guess one is that the benchmark ID is local to each single user. Can you please elaborate more on it, to understand how should we handle this ID generation, and what is the actual value we use internally and what the client (read user) sees?

Either way we use an userid or not to generate the key/ID to store the benchmark definition, what is described on the following issue should still hold: https://github.com/benchflow/data-transformers/issues/4. We can see this generated key/ID as the internal benchmark ID we store on our database, that is returned to the client by stripping out the part related to its username.

**Comment by VincenzoFerme** [comment]
_From @simonedavico on December 10, 2015 20:23_

I read the issue you referenced. From what I understood, the crucial part in guaranteeing good performance is the hash prepended to each key. Thus, it's better if we make sure that benchmarks with the same name uploaded by different users have a different hash; the same for different benchmarks uploaded by the same user. This is why I was considering to compute the hash out of both the benchmark name and the user id. Then, we may save the benchmarks as:
- `/hash/username/benchmarkname.zip`

and the default configuration of the benchmark as
- `/hash/username/benchmarkname/benchflow-benchmark.yml`

What do you think?

**Comment by VincenzoFerme** [comment]
@simonedavico ok, about the use of the `username`. Why not:
- `/hash/username/` **`benchmarkname`** `/benchmark.zip`

and
- `/hash/username/benchmarkname/benchflow-benchmark.yml`

?

**Comment by VincenzoFerme** [comment]
_From @simonedavico on December 10, 2015 22:2_

Yes, we can save it like that. Although for now I'm hashing only by using the benchmark name, and skipping the `/username/` part of the key since we don't have this info yet.

**Comment by VincenzoFerme** [comment]
_From @simonedavico on January 25, 2016 16:43_

This will be implemented properly as soon as we add authentication.

**Comment by VincenzoFerme** [comment]
_From @simonedavico on April 4, 2016 8:54_

We have implemented a `BenchFlowMinioClient` which formalises all the interactions of experiments-manager and drivers-maker with Minio. Everything is saved in the `benchmarks` bucket, and the keys structure is hierarchical, in the sense that it will always start with `benchmarks/{userId}/{benchmarkName}`; everything regarding the benchmark in general (such as original deployment descriptor and docker-compose files) can be found under this key, while everything regarding an experiment in particular can be found under `benchmarks/{userId}/{benchmarkName}/{experimentNumber}`. Similarly, everything regarding a trial can be found under `benchmarks/{userId}/{benchmarkName}/{experimentNumber}/{trialNumber}`. 

This is the list of keys used (where `{benchmarkId}` is actually `{userId}/{benchmarkName}`):
- The deployment descriptor sent at deploy of a benchmark is saved at `benchmarks/{benchmarkId}/original/docker-compose.yml`;
- The config file sent at deploy of a benchmark is saved at `benchmarks/{benchmarkId}/original/benchflow-benchmark.yml`;
- The config file for an experiment is saved at `benchmarks/{benchmarkId}/{experimentNumber}/benchflow-benchmark.yml`;
- The generated Faban config for a trial is saved at `benchmarks/{benchmarkId}/{experimentNumber}/{trialNumber}/run.xml`;
- The generated Faban driver for an experiment is saved at `benchmarks/{benchmarkId}/{experimentNumber}/driver.jar`;
- Models for a benchmark are saved at `benchmarks/{benchmarkId}/models/{modelName}`;

**Comment by VincenzoFerme** [comment]
Uniform the way the hash are structured for `tests` and `runs` so that:
- we have only a way to map the IDs we use internally, to component of minio path. That should be that every `.` is converted to `/` (in the Minio abstraction, or by the caller, or by something in between to centralise the logic). Moreover, we should have only the unique ids in the paths. E.g., now we have both the `experimentID` and the `trialID` for the collectors, and this does not make much sense.
- for the `runs` we should adopt a similar strategy we adopt for `test` to generate the hash, that basically is the hast is generated using the `testID` (concept that soon will we in the system through the `experiments-manager`, and now is already manager as it will be) so that all the resources belonging to a single test end up in the same bucket. This improve retrievability, and also performance of access.
- the hashing function should not concatenate the passed string, or if yes, we should sanitise everything to have both of the alternatives and everything in `commons`

**Comment by jeppe-style** [comment]
@VincenzoFerme I suggest we close this issue and continue as proposed here https://github.com/benchflow/benchflow/issues/132
