### ISSUE TITLE
Refactor the Experiment resource to internally create Trials

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#211]
_From @VincenzoFerme on April 6, 2016 14:30_

Refer to the following discussion: https://github.com/benchflow/experiments-manager/pull/28#discussion-diff-57511761

_Copied from original issue: benchflow/experiments-manager#29_

**Comment by jeppe-style** [comment]
@VincenzoFerme I think we can close this as this will be captured with the lifecycle we have defined.
