### ISSUE TITLE
Move the User Configuration to the BenchFlow Client

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#212]
_From @VincenzoFerme on April 9, 2016 16:38_

Refer to https://github.com/benchflow/experiments-manager/pull/28#discussion-diff-57511754

_Copied from original issue: benchflow/experiments-manager#30_

**Comment by jeppe-style** [comment]
@VincenzoFerme I'm not sure exactly what this is about (links don't work). I think we discussed having users being created on the test-manager service.

**Comment by VincenzoFerme** [comment]
@jeppe-style yes it is. The issue was about setting the default `BenchFlow` user in the client instead of the service.
