### ISSUE TITLE
Add the Trial_id as Field of the Trial Table

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#213]
_From @VincenzoFerme on April 9, 2016 16:57_

Once computed, the `trial_id` should be stored in the Trial table, so that we find it in the table when we need to select information about a trial.

_Copied from original issue: benchflow/experiments-manager#31_

**Comment by jeppe-style** [comment]
@VincenzoFerme It is captured now in the [TrialModel](https://github.com/benchflow/benchflow/blob/feature-experiment-manager/benchflow-experiment-manager/application/src/main/java/cloud/benchflow/experimentmanager/models/TrialModel.java).

I think we can close the issue.
