### ISSUE TITLE
Definition of the status for experiments and trials

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#214]
_From @simonedavico on April 12, 2016 15:38_

Regarding the status of the experiment:
- It is possible to retrieve the status of a single trial (which may be `QUEUED`, `RUNNING`, `COMPLETED` or `FAILED`);

Example:

``` json
{ 
    "trialId": "fooBenchmark.1.1", 
    "status": "COMPLETED" 
}
```
- It is possible to retrieve the aggregated status of an experiment (which may be `RUNNING` or `COMPLETED`), which also reports the status of the single trials. 

Example:

``` json
{
    "experimentId": "fooBenchmark.1",
    "status": "RUNNING",
    "trials": [
         { "trialId": "fooBenchmark.1.1", "status": "COMPLETED" },
         { "trialId": "fooBenchmark.1.2", "status": "RUNNING" }
    ]
}
```

_Copied from original issue: benchflow/experiments-manager#33_

**Comment by jeppe-style** [comment]
@VincenzoFerme this is covered when we return the [status of the test in the test-manager](https://github.com/benchflow/benchflow/blob/feature-test-manager/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/resources/BenchFlowTestResource.java#L174). I think that is sufficient and suggest we close this issue.
