### ISSUE TITLE
Discuss the way Experiments-Manager and Drivers-Makers interact

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#216]
_From @VincenzoFerme on May 12, 2016 14:29_

Discuss which are the interactions and how they are handled, e.g, synch, asynch

_Copied from original issue: benchflow/experiments-manager#36_

**Comment by jeppe-style** [comment]
@VincenzoFerme I think we have discussed this now and it is clear (sequence diagram). Suggest to close the issue.
