### ISSUE TITLE
Queue for managing multiple experiments

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#222]
_From @jeppe-style on October 2, 2016 9:49_

@VincenzoFerme, from what I can see currently all experiments (they are for some reason called tests in (parts of) the code(?)) are put in a thread pool, and then all trials are executed in parallel until they have completed. After the experiment has been submitted it is then possible to get the status of the experiment and individual trials.

**_Discussion_**: Currently we rely on Faban's internal queue to schedule trials. We would like to have more control so therefore we want to add a queue (see screenshot). Some functionality in the EM will be moved to a new component called Faban Manager.

<img width="1083" alt="screen shot 2016-10-04 at 11 53 42" src="https://cloud.githubusercontent.com/assets/8646217/19069908/3ec1436c-8a29-11e6-83c0-1c965515e1d3.png">

If I understand correctly the BenchFlow-Client submits the experiments to the Experiments-Manager. It seems though that they currently are not aligned since for instance there is no `/deploy` API call on EM. Also all calls from the client to EM is done by polling.

**_Discussion_**: Yes, they are currently not aligned. By introducing Faban Manager and event bus we can avoid polling. A new client will be implemented.

I suggest to first work out a sequence diagram of how we want the interaction to happen when we add the queue, and then based on that make the architecture for EM. We can then already in this include the test orchestrator. 

**_Discussion_**: (see photo)

![img_1351](https://cloud.githubusercontent.com/assets/8646217/19071576/1c38323a-8a31-11e6-84ed-cef07a50e0bc.png)

I think it would also be nice to notify the caller when an experiment has finished, specially since we would like to be able to make decisions regarding space exploration.

**_Discussion_**: Notification will be done through Faban Manager and the event bus.

Could you please also clarify to me what is the difference between test and experiment in the context of BenchFlow? To me it seems they are mixed a bit.

**_Discussion_**: Tests consists of experiments. Experiments consists of trials.

_Copied from original issue: benchflow/experiments-manager#47_

**Comment by jeppe-style** [comment]
@VincenzoFerme I think we can close this since we already have different interactions planned or already implemented.
