### ISSUE TITLE
Move Responsibility for Storing file on Minio Here

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#232]
_From @VincenzoFerme on August 22, 2016 10:40_

Move Responsibility for Storing file on Minio Here from the Experiments-Manager

_Copied from original issue: benchflow/test-orchestrator#4_

**Comment by VincenzoFerme** [comment]
_From @simonedavico on August 22, 2016 18:10_

I think there is nothing to move. The implemented components only store their own files on Minio.
The only exception is the `models` folder, that is uploaded at test level from the `experiments-manager` since we don't have a `test-orchestrator` yet.

**Comment by VincenzoFerme** [comment]
Ok then the `models` folder should be moved, as well as `test` level files that are the artefacts entry the user. Then the other components will save their own version of that artefacts.

**Comment by jeppe-style** [comment]
@VincenzoFerme this is handled by the `test-manager` that we are right now including in this repo. Suggest to close the issue.
