### ISSUE TITLE
Add Code Checker to Java Services

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#242]
Add Code Checker to the services referenced with labels. 

Work started in https://github.com/benchflow/benchflow/pull/237, and to be completed for all the services

**Comment by VincenzoFerme** [comment]
@igormoreno evaluate if we can move the following files in a subdirectory of the `devoid` folder named `code-checker` (check against our maven setup and codacy):

- https://github.com/benchflow/benchflow/blob/devel/benchflow_java_checks.xml
- https://github.com/benchflow/benchflow/blob/devel/scalastyle-config.xml

**Comment by igormoreno** [comment]
i'm waiting for #279

**Comment by VincenzoFerme** [comment]
Document: https://github.com/benchflow/benchflow/pull/336#issuecomment-301334777
