### ISSUE TITLE
Integration tests with Docker Compose does not run with maven properly

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#254]
When running integration tests with docker compose integration using `mvn verify` there are in some (random) tests `java.net.ConnectException: Connection refused (Connection refused)` errors, which makes the test fail.

When the same tests are run with the wercker pipeline (e.g. `wercker dev --pipeline=build-benchflow-experiment-manager`) it is fine. Also running individual tests seems to work fine.

**Comment by VincenzoFerme** [comment]
We also need to double check that the services are started only at the beginning of the test

**Comment by jeppe-style** [comment]
Fixed for test-manager in https://github.com/benchflow/benchflow/pull/266

**Comment by VincenzoFerme** [comment]
Fixed for experiment manager in https://github.com/benchflow/benchflow/pull/291
