### ISSUE TITLE
Rename PEM_ADDRESS to EM_ADDRESS configuration variable

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#294]
Rename: https://github.com/benchflow/benchflow/blob/devel/benchflow-test-manager/configuration.yml#L70

**Comment by jeppe-style** [comment]
This was fixed in this commit (merged with `development`) https://github.com/benchflow/benchflow/commit/3169f96597122c1c799e101f6ba8b10b180ebafd#diff-13a42be4dcea0380504a7fac879be08aL70
