### ISSUE TITLE
Refactor TaskController to TaskScheduler and Add Running and Ready Queues

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#319]
In the experiment-manager and test-manager we want to add two queues for test/experiments:
- _ready queue_: when an test/experiment has completed the start state it will be put here
- _running queue_: a queue that contains (for now one) the currently running test/experiment

In addition the `TaskScheduler` will have one `ExecutorService` that executes the different tasks according to available resources.

We have these two queues to control how many test/experiments can run at the same time. They can be `BlockingQueue`s (see [JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html)). The two queues are FIFO.

The general idea is to keep all the business logic/control flow in the `TaskScheduler`.

As a request comes in a start task is scheduled on the executor service. When finished the test/experiment ID is put in the _ready queue_ and its state changed to `READY`.

Once a test/experiment is `READY` it is checked if the _running queue_ is free. If it is, the state is changed to `RUNNING` and the test/experiment is executed until it has reached state `TERMINATED` or `WAITING` (only test manager - when user input is needed). Otherwise nothing happens.

When a test/experiment is `paused` the state changes to `READY`, however, it is not put in the _ready queue_. Once the input is given to continue execution it is added to the _ready queue_ (by calling `handleExperimentState(...)`).

Once the test/experiment has reached the state `TERMINATED`, or `WAITING` it is removed from the _running queue_ and the next test/experiment in the _ready queue_ is processed.

**Comment by VincenzoFerme** [comment]
@jeppe-style in the description above you mention the `WAITING` state, but this state is only related to the `test-manager` in https://github.com/VincenzoFerme/benchflow-temporary-documentation/blob/master/roadmap/Jesper/architecture/lifecycle-sequence.pdf. What is the equivalent in the `experiment-manager` for scheduling the next trial? Is it the `ABORTED` state?

**Comment by jeppe-style** [comment]
Yes - you are right it, is not clear. I updated the text above with some more clarification also about `pausing`. There is no `WAITING` state for the experiment.

**Comment by VincenzoFerme** [comment]
You change make me thing that we need a `PAUSED` state.

**Comment by jeppe-style** [comment]
When would that be the case?

**Comment by VincenzoFerme** [comment]
When it is `PAUSED` because, they now switch to `READY` but they do not go in the ready queue. To me something in a given state, has always to have the same behaviour and the same things have to happen.

**Comment by jeppe-style** [comment]
Fixed for experiment-manager in https://github.com/benchflow/benchflow/issues/356

**Comment by jeppe-style** [comment]
About `PAUSED` I think we can open a separate issue and discuss there. Don't think it is necessary for this week.

**Comment by VincenzoFerme** [comment]
Go ahead in opening a separate issue.

**Comment by jeppe-style** [comment]
Pausing is now covered in this issue https://github.com/benchflow/benchflow/issues/364
