### ISSUE TITLE
Test Termination Criteria - Max Time

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#337]
```
configuration:
  termination_criteria:
    test:
      max_running_time: { String : <amount of time + unit> }
```
When specified in the test definition there should be a timeout triggered after the specified time has passed so that the test can be stopped (any running experiments must also be stopped) and set to state `Terminated` `Partially Complete`.

@VincenzoFerme when do we start to count this time? When the test has ben submitted by the user and become part the lifecycle? Another option is to only count the time it is actually running (state=running), e.g., we do not count the waiting time. => Count only the running time

We can use a [ScheduledExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html) to schedule a `Runnable` (`TestTimeout`) that notifies the Scheduler that the termination criteria has been reached after a given delay. 

When submitting the `Runnable` we get a `Future` that can be stored in a `ConcurrentMap<String Future>` (key=testID). In this way we can remove the `TestTimeout` if the test completes before the max time.

The `ScheduledExecutorService` can be instantiated in the application and fetched in the same way as the `TaskExecutorService`.

**Comment by VincenzoFerme** [comment]
About your question on how to count time, i would:

- Rename the field to `max_running_time`
- Count only the running time

This way for now we just support the running time, skipping the queue because anyway now we execute an experiment at a time.

Ok for the way you plan to implement it. Is the following a possible solution to avoid using two executor services https://docs.oracle.com/javase/7/docs/api/java/util/TimerTask.html?

**Comment by jeppe-style** [comment]
I updated the first comment according to your suggestions.

I was reading about `TimerTask`. What I understood is that you have a `Timer` that schedules the `TimerTasks` on a single thread. For me then the difference is that you have a scheduler with one or more threads. In the [documentation for the `Timer`](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html) they write:

_"Java 5.0 introduced the java.util.concurrent package and one of the concurrency utilities therein is the ScheduledThreadPoolExecutor which is a thread pool for repeatedly executing tasks at a given rate or delay. It is effectively a more versatile replacement for the Timer/TimerTask combination, as it allows multiple service threads, accepts various time units, and doesn't require subclassing TimerTask (just implement Runnable). Configuring ScheduledThreadPoolExecutor with one thread makes it equivalent to Timer."_

I think the `ScheduledThreadPoolExecutor` is therefore a preferred solution since it is more flexible and has a bit less overhead as we do not need to subclass `TimerTask`.

**Comment by VincenzoFerme** [comment]
So if I got it right we are going to have tests waiting in a queue to go to the running state, then according to the type of task, you are going to schedule the thread in one of the two queues you handle, right?

**Comment by VincenzoFerme** [comment]
We need to think if it makes sense to kill the current executing experiment, or just let it finish and do not schedule more. Because there is the risk you lose even more time, because you throw away work.

**Comment by jeppe-style** [comment]
maybe we should discuss this in person?

**Comment by jeppe-style** [comment]
- Timeout is an event scheduled as `Runnable` (`TimeoutTask`) in the `ScheduledThreadPoolExecutor` (`testID` is a parameter) => `TimeoutExecutorService`
- `TaskScheduler` receives the timeout and decides what to do => same way as abort test (e.g. kill trial on Faban (needs testing what happens when calling kill on Faban (when does it return?)) and then undeploy on Faban client)
-  `TaskScheduler` removes the `TimeoutTask` when test has reached the `terminated` state

possible extension: 
- don't schedule a new experiment/trial if expected that the execution time exceeds the time of the timeout
- impact the selection strategy
