### ISSUE TITLE
Add Generation of Docker Compose from Parameters

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#341]
as title

support for:
- memory
- CPU
- environment variables

**Comment by VincenzoFerme** [comment]
@jeppe-style is this closed by https://github.com/benchflow/benchflow/pull/368 or does it still need improvements?

**Comment by jeppe-style** [comment]
@VincenzoFerme that is fine - there is the issue https://github.com/benchflow/benchflow/issues/380 that covers missing parts
