### ISSUE TITLE
Add Generation of Experiment from Configuration Parameters

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#342]
as per title

**Comment by jeppe-style** [comment]
This has actually already been implemented since it is currently only needed for number of users.

@VincenzoFerme the issue can be closed.

**Comment by VincenzoFerme** [comment]
Is it implemented for all the all the configuration parameters we decided to support?

**Comment by jeppe-style** [comment]
Yes, cpu, memory and environment variables only influences the docker-compose file so those are handled separately in https://github.com/benchflow/benchflow/issues/341
