### ISSUE TITLE
Generate and store exploration space

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#370]
Precompute exploration spaces for `one-at-a-time` and `random-breakdown` and make them available through API call

This has been changed (see below)

**Comment by VincenzoFerme** [comment]
Why not also for the other strategies?

**Comment by jeppe-style** [comment]
Because they cannot be pre-computed

**Comment by VincenzoFerme** [comment]
Why not, the full space should always be possible to be precomputed.

**Comment by jeppe-style** [comment]
but only in `one-at-a-time` or `random` order

I'm thinking now that also random order we actually don't need to precompute, but just keep a list with the order of experiments (e.g. from 0 to exploration space size) which we can shuffle to give us randomness. This is easy to do in the test-manager.

**Comment by VincenzoFerme** [comment]
Probably I miss what you mean with `exploration-space` then. Can you explain me what are you precomputing here, for which strategies you can precompute and for which no and why? Thanks :)

**Comment by jeppe-style** [comment]
Yes! Sorry I'm very much into it so it is difficult to step out.

In general I define an instance that summarizes the exploration space defined by the user in the test definition. Here each dimension (e.g. memory, number of users) is stored as lists with all possible values for that dimension.

From that I define an instance to keep the state of the exploration space, e.g. with capacity to store all possible combinations of dimensions. In this instance I keep a list for each dimension that has the size of all possible combinations. If we have a `one-at-a-time` selection strategy I can precompute the values, e.g. index 0 in the list corresponds to experiment 1, index 1 in the list corresponds to experiment etc. This would is also possible for `random` selection strategy by shuffling the indices, however, we might just want to keep a separate list with the order which we then can shuffle.
For other strategies I insert `-1` into the given indices to indicate that this has not yet been executed, since for other exploration strategies we want to decide the configuration of the next experiment based on the previous results. Here we could also used the precomputed order, however, we then would need to search through to find the particular configuration we want to execute next.

It is a bit difficult to explain this in written, so maybe it is easier to discuss when we meet.

**Comment by jeppe-style** [comment]
Outcome of discussion:
**DSL**
- provides an API to generate the complete exploration space (e.g. the matrix we talked about), where a row corresponds to a configuration of an experiment
- provides an API to get the next experiment bundle (definition, docker compose) based on an exploration space, index to the row, test definition and docker compose
- provides an API to get the next experiment bundle and index to the row (definition, docker compose) based on an exploration space, an experiment configuration, test definition and docker compose

The exploration space is computed using the `cartesian product`.

**Test- Manager**
- keeps track of executed experiments by storing the row indices of executed experiments in a list
- selection strategy determines next experiment to execute (either by index or configuration) and requests corresponding experiment bundle from the DSL (as above)

**Comment by VincenzoFerme** [comment]
Closed by https://github.com/benchflow/benchflow/pull/371 and https://github.com/benchflow/benchflow/pull/394
