### ISSUE TITLE
Add Possibility to Start Service in Test Mode

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#385]
To be able to perform basic component testing of a service it should be able to start in a test mode to mock external services, e.g. Faban, to test the functionality without actually running an experiment.

This should be done by adding the following in the configuration file:
```
testMode:
  mockFaban: ${env.MOCK_FABAN!false?c}
```

When the service starts in this mode with the boolean flag for a given service set to `true` that service  should be mocked. The mode can also be set as an environment variable `MOCK_FABAN`.  `?c` is need to be able to [convert from a string to boolean](http://freemarker.org/docs/ref_builtins_boolean.html#ref_builtin_c_boolean)

To control how the mock should behave we create scenarios. The mocked service understands the scenario by the name of the experiment, e.g., if the name is `scenario1` then the mock knows it should simulate scenario 1.

This is done to make it easier to control the expected behavior.

**Comment by VincenzoFerme** [comment]
@jeppe-style give a look at the following comment, because can help with this as well: https://github.com/benchflow/benchflow/issues/348#issuecomment-305913034

**Comment by jeppe-style** [comment]
@VincenzoFerme I had a look, however, I don't see how this can help in our case since we want to control it from the configuration and the example is about overriding the configuration for testing purposes and insert mocks that have been constructed in the test classes.

**Comment by VincenzoFerme** [comment]
You need to define a configuration section that works both when the test mode is needed, but also when it is not needed. I mean, the info about the testing (if enabled or not) have to be specified using an environment variable as well.

**Comment by jeppe-style** [comment]
Yes I agree and already had included that in the implementation. I updated the initial note accordingly.

**Comment by VincenzoFerme** [comment]
Closed by https://github.com/benchflow/benchflow/pull/392
