### ISSUE TITLE
Update DSL optional (for the Model) values

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#401]
In order to match what is implemented in the thesis ([slack discussion](https://benchflow.slack.com/conversation/G5GCXP63D/p1497120251698733)) change the following:
- [x] workload execution should not be optional
- [x] termination criteria should not be optional (experiment needs to be defined, other optional)
- [x] data collection for client side faban should not be optional
- [x] number of users should not be optional for experiment

**Comment by VincenzoFerme** [comment]
@jeppe-style: which are the ones that are optional also for the user?

**Comment by jeppe-style** [comment]
The ones that have default values as specified here https://github.com/VincenzoFerme/benchflow-temporary-documentation/blob/master/roadmap/Jesper/dsl.md

For this PR:
- data collection for client side faban
