### ISSUE TITLE
N/A Faban Random Failure has to be threatened as Re-Execution of Trial

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#420]
See title

**Comment by jeppe-style** [comment]
@VincenzoFerme this requires additional information in the [`RunStatus.java`](https://github.com/benchflow/benchflow/blob/devel/benchflow-faban-client/src/main/java/cloud/benchflow/faban/client/responses/RunStatus.java)

**Comment by VincenzoFerme** [comment]
I just added a pull request to provide these additional data, that must be accessed using a different API: `RunInfo`.

**Comment by VincenzoFerme** [comment]
You can now use the new `RunInfo` command added in https://github.com/benchflow/benchflow/issues/434 to improve the way you handle Faban `ResultStatus`. I suggest you to open an issue, or update an existing one, so that you define what happens according to Faban `ResultStatus` and `RunInfo`.

**Comment by jeppe-style** [comment]
Issue added https://github.com/benchflow/benchflow/issues/440

**Comment by VincenzoFerme** [comment]
Closed by https://github.com/benchflow/benchflow/pull/434, and continuation in https://github.com/benchflow/benchflow/issues/440 for the `test-manager`.
