### ISSUE TITLE
Add links in REST API response objects

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#446]
**Experiment Status**
Experiment Model
- [x] link to experiment bundle for driver-maker on minio (`driverMakerExperimentBundle: URL`)

Trial Model
- [x] link to faban run status (`fabanRunStatus: URL`)

Related to https://github.com/benchflow/benchflow/issues/128

**Comment by VincenzoFerme** [comment]
See https://github.com/benchflow/benchflow/issues/445#issuecomment-310144934

**Comment by VincenzoFerme** [comment]
What is left from this Issue is now documented in https://github.com/benchflow/benchflow/issues/128#issuecomment-319903870
