### ISSUE TITLE
Enable enumerations use in Java

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#447]
It seems the easiest to use Java `enum` instead of the Scala `enumeration`. If we use it like below (`BytesUnit` example in a `BytesUnit.java` file) we can use it in the same way as we use Scala `enumeration` now:

```Java
public enum BytesUnit {
  BYTES("b"),
  KILO_BYTES("k"),
  MEGA_BYTES("m"),
  GIGA_BYTES("g");

  private final String stringValue;

  JavaBytesUnit(String stringValue) {
    this.stringValue = stringValue;
  }

  @Override
  public String toString() {
    return this.stringValue;
  }

}
```

Related to https://github.com/benchflow/benchflow/issues/391

**Comment by VincenzoFerme** [comment]
So we do not need Scala Enumeration specific functionalities, right?

**Comment by jeppe-style** [comment]
yes - in this way we get all the functionality we need as well as Java compatibility directly.
