### ISSUE TITLE
Instantiating JavaCompatExplorationSpace from TM fails

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#477]
When retrieving the exploration space from the DB we get a [`MongoCompatibleExplorationSpace`](https://github.com/benchflow/benchflow/blob/14ea1a3e9919c3401ab5e6abfe0c267c9ba4274f/benchflow-test-manager/application/src/main/java/cloud/benchflow/testmanager/models/explorationspace/MongoCompatibleExplorationSpace.java) which contains a method `toJavaCompat` that converts the object to a `JavaCompatExplorationSpace ` defined in the DSL. In some cases (for instance when calling interactively using Evaluate Expression in IntelliJ) this throws a runtime exception or silently fails and stops the execution (when running integration tests):
```{Java}
No such instance method: 'cloud.benchflow.dsl.explorationspace.JavaCompatExplorationSpaceConverter$$JavaCompatExplorationSpace cloud.benchflow.testmanager.models.explorationspace.MongoCompatibleExplorationSpace.toJavaCompat ()'
```

When called in [`ConvertersTest.testStoringRetrievingExplorationSpace`](https://github.com/benchflow/benchflow/blob/14ea1a3e9919c3401ab5e6abfe0c267c9ba4274f/benchflow-test-manager/application/src/test/java/cloud/benchflow/testmanager/services/internal/dao/converters/ConvertersTest.java#L114) it works as expected.

**Comment by VincenzoFerme** [comment]
At some point we also said we should move the Java Conversion out of the DSL, if it is not possible to specify it in the Scala object itself using a method (or always).

**Comment by jeppe-style** [comment]
This has been adjusted in PR https://github.com/benchflow/benchflow/pull/519 which also should fix this issue. Suggest to close this issue.
