### ISSUE TITLE
Test Life Cycle TERMINATING State

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#499]
Add new state `TERMINATING` where we wait when a test is about to be terminated but we still need to get an update from the EM about the currently running experiment.

Before entering the `TERMINATING` state:
-  an `abort` of the currently running experiment (if any) is sent to the EM

Once in the state `TERMINATING`:
- waits for EM to notify that any running experiment has reached the state `TERMINATED`
- once notified the test is set as `TERMINATED`: `PARTIALLY COMPLETE` and handled as regular `TERMINATED` test

see updated life cycle diagram: https://github.com/VincenzoFerme/benchflow-temporary-documentation/blob/master/roadmap/Jesper/architecture/diagrams/svg/Test%20Life%20Cycle__BenchFlow%20Test%20Life%20Cycle_0.svg

**Comment by VincenzoFerme** [comment]
> Before entering the TERMINATING state:
>
> - an abort of the currently running experiment (if any) is sent to the EM

This should happen in the state (or `TERMINATE` handler) preceding the `TERMINATING` state

**Comment by VincenzoFerme** [comment]
Needs also to handle the response, to be sure the requested operation has been accepted but the called service. See for example: https://github.com/benchflow/benchflow/pull/474#discussion_r126484133
