### ISSUE TITLE
Improve aborting of experiment

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#500]
When an experiment is running on Faban the Faban Manager polls for the result, however, with the current implementation it keeps the lock on the task scheduler and thus the experiment cannot be aborted. 

Solution
- add an API resource PUT `/result` on `/v1/users/{username}/tests/{testName}/{testNumber}/experiments/{experimentNumber}/trials/{trialNumber}` that takes the Faban result object as a parameter
  - when a request is received the `TaskScheduler` is passed the data (similar as in the TM when receiving an experiment result)
- Change the Faban Manager to call the API so that it easily can be changed into a separate service
- make tests to ensure that an experiment can be aborted during execution (waiting for Faban to complete execution of current trial)

**Comment by VincenzoFerme** [comment]
It is not clear what the difference is going to be compared to what we have now. Is it that the Faban Manager is going to poll the status in background and ping the API when the state changes? If yes, I would call the API only when the new state is different compared to the previous one that has been obtained from Faban.

**Comment by jeppe-style** [comment]
yes, that is more or less what the issue is about. The REST API is only called once after the polling is complete, so there is only the final state from Faban.

**Comment by VincenzoFerme** [comment]
Whit the last changes I made the abort method not synchronised. Moreover what you could do is that you have a background task that handles the polling of Faban, that then reactivate the lifecycle. Similar to what we do while waiting for an experiment to complete in the test-manager when we reach `HANDLE_EXPERIMENT_RESULT`, but in the experiment-manager case between Threads in the same service, instead two different services. This fits also more or less with what we discussed above.
