### ISSUE TITLE
Gather Faban Status into one object in the Experiment Status

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#503]
Enable the possibility to track the Faban results for all executions

- collect the faban related info into one object for each trial (e.g. store in separate class `FabanInfo` )
```{json}
{
    fabanRunID: <String>
    fabanStatus: <RunStatus.StatusCode>
    fabanResult: <RunInfo.Result>
    fabanRunStatus: <String>
}
```
- store it for each execution (e.g. also for re-execution) so that the history can be tracked if the user wants (in a list) (update `TrialModel` accordingly)
```
fabanInfo: [<fabanObject execution 0>, <fabanObject execution 1>... ]
```

**Comment by VincenzoFerme** [comment]
Execution, and re-execution need to be clearly identifiable so that the users knows if it was the same trial that has been re-executed, or a new executed trial.

**Comment by jeppe-style** [comment]
@VincenzoFerme a new executed trial will have a different trial-ID so this only applies to one trial
