### ISSUE TITLE
Errors in interactions with Driver-Maker and Faban-Manager in the StartTask should go to Error state

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#504]
as per title
- [x] `DriversMakerService.generateBenchmark` should throw an exception (`BenchMarkGenerationException`) if the benchmark cannot be generated (retry connection 3 times)
- [x] `FabanManagerService.deployExperimentToFaban` should throw an exception (`BenchMarkDeploymentException`) if `fabanClient.deploy` throws an exception
- [x] the above exceptions should cause a return of `false` in the `StartTask` like the other deployment errors
- [x] add test to test functionality

**Comment by VincenzoFerme** [comment]
This should happen in the interactions with any service, and any interaction (e.g., also the `run` on Faban). The idea is that if something goes wrong, and the end-to-end execution cannot be completed as expected, that has to be reported to the user.

**Comment by VincenzoFerme** [comment]
The number of retries should be configurable in the DropWizard configuration file for each dependent service.
