### ISSUE TITLE
Not all experiments are generated in the exploration space

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#506]
Sometimes (in [use case 7](https://github.com/benchflow/benchflow/issues/403)) not all experiments are generated. It seems there is an issue with generating the experiment number. 

solution:
- change storage of experiments in the test model to `HashMap`
- add more tests to ensure experiment number generation is correct and stored correctly in the DB
- check that there is no issue with concurrency reading/writing to the DB (e.g. not overwriting previous experiment)

**Comment by VincenzoFerme** [comment]
Fixed in https://github.com/benchflow/benchflow/pull/527
