### ISSUE TITLE
Use CamelCase Notation for all the Elements of the benchlow-test

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#54]
_From @VincenzoFerme on August 22, 2016 15:33_

E.g., also for https://github.com/benchflow/test-definition-model/blob/dev/src/test/resources/benchflow-test.yml#L44

This because most of the elements are camelCase. Then think about aligning to the way Docker Compose approach it.

_Copied from original issue: benchflow/test-definition-model#4_

**Comment by VincenzoFerme** [comment]
_From @simonedavico on August 22, 2016 18:7_

The `dev` branch is out of date, since its history is broken. 
This has already been taken care of.

**Comment by VincenzoFerme** [comment]
Ok, when you merge the changes, mark this issue as fixed.

**Comment by jeppe-style** [comment]
can we close this since we now have v1 of the DSL?
