### ISSUE TITLE
Decision about the Programming Language and Framework to Use

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#86]
_From @VincenzoFerme on May 11, 2016 14:31_

Evaluate PRO and CONS according to our [requirements](https://github.com/benchflow/data-manager/issues/1) of:
- Scala (and Actors, [correctly used](https://www.chrisstucchio.com/blog/2013/actors_vs_futures.html))
- Java

Then the web framework:
- http://www.dropwizard.io/0.9.2/docs/getting-started.html (we already have experience and some projects using it, also mixing Java and Scala)
- https://www.playframework.com

_Copied from original issue: benchflow/data-manager#3_

**Comment by VincenzoFerme** [comment]
_From @igormoreno on May 17, 2016 10:11_

## Reference

### Actors

Erlang for Concurrency, Jim Larson:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.207.3752&rep=rep1&type=pdf

Scala Actors: Unifying Thread-based and Event-based Programming:
https://infoscience.epfl.ch/record/128406/files/haller_tcs2008_accepted.pdf

### Reactive programming

https://class.coursera.org/reactive-002/lecture

### Lambdas and streams: Java 8 vs. Scala

https://github.com/nosheenzaza/bug-life-java8/blob/master/VoxxedDaysSlidesJava8.pdf

### Play

Asynchronous HTTP programming:
(Talks about Asynchronous results, Streaming HTTP responses, Comet, WebSockets)
https://www.playframework.com/documentation/2.5.x/ScalaAsync

### Metrics and health checks

Use dropwizard metrics (that includes health checks) separately:
http://metrics.dropwizard.io
https://github.com/erikvanoosten/metrics-scala
https://github.com/kenshoo/metrics-play

### Microservices templates

with Play:
http://www.lightbend.com/activator/template/playing-microservices

with Akka:
http://www.lightbend.com/activator/template/akka-http-microservice

**Comment by VincenzoFerme** [comment]
Lets go for the Play framework. We can evaluate it on a real project and if it not suited for us, it's easy to switch back to Dropwizard mixed with Akka and the Actor model.

**Comment by igormoreno** [comment]
@VincenzoFerme can we close this?
